django_sample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('predictor/', include('predictor.urls'))
]

predictor/urls.py
from django.urls import path
from . import views

app_name = 'predictor'

urlpatterns = [
    path("home/", views.home, name = "home"),
    path("models/", views.models, name = "models"),
    path("model1/", views.model1, name = "model1"),
    path("model2/", views.model2, name = "model2"),
    path("model3/", views.model3, name = "model3")
    
]

predictor/models.py
from django.db import models

# Create your models here.

predictor/forms.py
from django import forms
#/content/drive/MyDrive/DISP/Programming/models/('IFNg', 'IL-10', 'TNF-a', 'G-CSF').model
class Model1Form(forms.Form):#IFNg,IL-6,IL-17A,IL-1b
    IFNg = forms.FloatField(required=True)
    IL10 = forms.FloatField(required=True)
    TNFa = forms.FloatField(required=True)
    GCSF = forms.FloatField(required=True)

    


class Model2Form(forms.Form):#
    IL6 = forms.FloatField(required=True)
    IL4 = forms.FloatField(required=True)
    IL1b = forms.FloatField(required=True)
    TNFa = forms.FloatField(required=True)
    GCSF = forms.FloatField(required=True)

class Model3Form(forms.Form):#
    IL6 = forms.FloatField(required=True)
    IL2 = forms.FloatField(required=True)
    IL17A = forms.FloatField(required=True)
    IL1b = forms.FloatField(required=True)
    GCSF = forms.FloatField(required=True)
    

predictor/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from . forms import Model1Form, Model2Form, Model3Form
import os
from django.conf import settings
import joblib
from django.conf import settings
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import pickle
import xgboost as xgb
import numpy as np

#loading models
def load_model1():
    model_path = os.path.join(settings.BASE_DIR, 'predictor/models/', 'model1.model')
    model1 = xgb.Booster(model_file=model_path)
    return model1

def load_model2():
    model_path = os.path.join(settings.BASE_DIR, 'predictor/models/', 'model2.model')
    model2 = xgb.Booster(model_file=model_path)
    return model2

def load_model3():
    model_path = os.path.join(settings.BASE_DIR, 'predictor/models/', 'model3.model')
    model3 = xgb.Booster(model_file=model_path)
    return model3


# Create your views here.

def home(request):
    return render(request, 'predictor/home.html')

def models(request):
    return render(request, 'predictor/models.html')

def model1(request):
    predictor_model1 = load_model1()

    if request.method == 'POST':
        form = Model1Form(request.POST)
        if form.is_valid():
            collected_data = form.cleaned_data

            inputs = [collected_data[field] for field in collected_data]
            inputs = np.array(inputs)
            inputs = inputs.reshape(1, -1)
            scaler = StandardScaler()
            inputs = scaler.fit_transform(inputs)
            inputs = xgb.DMatrix(inputs)

            output = ""

            prediction = predictor_model1.predict(inputs)

            if prediction > 0.5:
                output = "Severe"
            else:
                output = "Non-severe"
            
            return render(request, "predictor/results.html", {'output':output})
    else:
        form = Model1Form()
    
    return render(request, "predictor/model1.html", {'form': form})

def model2(request):
    predictor_model1 = load_model2()

    if request.method == 'POST':
        form = Model2Form(request.POST)
        if form.is_valid():
            collected_data = form.cleaned_data

            inputs = [collected_data[field] for field in collected_data]
            inputs = np.array(inputs)
            inputs = inputs.reshape(1, -1)
            scaler = StandardScaler()
            inputs = scaler.fit_transform(inputs)
            inputs = xgb.DMatrix(inputs)

            output = ""

            prediction = predictor_model1.predict(inputs)

            if prediction > 0.5:
                output = "Severe"
            else:
                output = "Non-severe"
            
            return render(request, "predictor/results.html", {'output':output})
    else:
        form = Model2Form()
    
    return render(request, "predictor/model2.html", {'form': form})

def model3(request):
    predictor_model1 = load_model3()

    if request.method == 'POST':
        form = Model3Form(request.POST)
        if form.is_valid():
            collected_data = form.cleaned_data

            inputs = [collected_data[field] for field in collected_data]
            inputs = np.array(inputs)
            inputs = inputs.reshape(1, -1)
            scaler = StandardScaler()
            inputs = scaler.fit_transform(inputs)
            inputs = xgb.DMatrix(inputs)

            output = ""

            prediction = predictor_model1.predict(inputs)

            if prediction > 0.5:
                output = "Severe"
            else:
                output = "Non-severe"
            
            return render(request, "predictor/results.html", {'output':output})
    else:
        form = Model3Form()
    
    return render(request, "predictor/model3.html", {'form': form})

predictor/templates/predictor/home.html
{% extends 'base.html'%}

{% block content %}

<p>Welcome to the Early Diagnostic Tool for Sepsis</p>

{%endblock%}

predictor/templates/predictor/model1.html
{% extends 'base.html'%}



{% block content %}

<style>
    .form-container {
        border: 1px solid #ccc;
        padding: 10px;
        width: fit-content; /* Adjust width as needed */
        margin: auto;
    }

    .form-field {
        margin-bottom: 10px;
    }

    .form-label {
        display: inline-block;
        width: 150px; /* Adjust width as needed */
    }
</style>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-field">
        <label for="id_field1" class="form-label">IFNg:</label>
        {{ form.IFNg }}
    </div>

    <div class="form-field">
        <label for="id_field2" class="form-label">IL10:</label>
        {{ form.IL10 }}
    </div>
    <div class="form-field">
        <label for="id_field3" class="form-label">TNFa:</label>
        {{ form.TNFa }}
    </div>
    <div class="form-field">
        <label for="id_field4" class="form-label">GCSF:</label>
        {{ form.GCSF }}
    </div>

    <br>
    <button type="submit">Submit</button>
</form>
{% endblock %}

predictor/templates/predictor/model2.html
{% extends 'base.html'%}



{% block content %}

<style>
    .form-container {
        border: 1px solid #ccc;
        padding: 10px;
        width: fit-content; /* Adjust width as needed */
        margin: auto;
    }

    .form-field {
        margin-bottom: 10px;
    }

    .form-label {
        display: inline-block;
        width: 150px; /* Adjust width as needed */
    }
</style>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-field">
        <label for="id_field1" class="form-label">IL6:</label>
        {{ form.IL6 }}
    </div>

    <div class="form-field">
        <label for="id_field2" class="form-label">IL4:</label>
        {{ form.IL4 }}
    </div>

    <div class="form-field">
        <label for="id_field3" class="form-label">IL1b:</label>
        {{ form.IL1b }}
    </div>

    <div class="form-field">
        <label for="id_field4" class="form-label">TNFa:</label>
        {{ form.TNFa }}
    </div>
    <div class="form-field">
        <label for="id_field5" class="form-label">GCSF:</label>
        {{ form.GCSF }}
    </div>

    <br>
    <button type="submit">Submit</button>
</form>
{% endblock %}

predictor/templates/predictor/model3.html
{% extends 'base.html'%}



{% block content %}

<style>
    .form-container {
        border: 1px solid #ccc;
        padding: 10px;
        width: fit-content; /* Adjust width as needed */
        margin: auto;
    }

    .form-field {
        margin-bottom: 10px;
    }

    .form-label {
        display: inline-block;
        width: 150px; /* Adjust width as needed */
    }
</style>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-field">
        <label for="id_field1" class="form-label">IL6:</label>
        {{ form.IL6 }}
    </div>

    <div class="form-field">
        <label for="id_field2" class="form-label">IL2:</label>
        {{ form.IL2 }}
    </div>

    <div class="form-field">
        <label for="id_field3" class="form-label">IL17A:</label>
        {{ form.IL17A }}
    </div>

    <div class="form-field">
        <label for="id_field4" class="form-label">IL1b:</label>
        {{ form.IL1b }}
    </div>
    <div class="form-field">
        <label for="id_field5" class="form-label">GCSF:</label>
        {{ form.GCSF }}
    </div>

    <br>
    <button type="submit">Submit</button>
</form>
{% endblock %}

predictor/templates/predictor/models.html
{% extends 'base.html'%}
{% block content %}
<style>
    table {
        border-collapse: collapse;
        width: 100%;
        border: 2px solid #ddd; /* Add a border around the table */
    }

    th, td {
        padding: 12px; /* Increase padding for better spacing */
        text-align: left;
        border-bottom: 1px solid #ddd; /* Add bottom border to cells */
    }

    th {
        background-color: #f2f2f2;
        border-top: 2px solid #ddd; /* Add top border to header cells */
    }

    tr:hover {
        background-color: #f5f5f5; /* Add a subtle hover effect */
    }
</style>


<table>

    <thead>
 
        <tr>
 
            <th>Biomarkers</th>
 
            <th>Accuracy</th>
 
            <th>AUC</th>
 
            <th>Action</th>  
 
        </tr>
 
    </thead>
 
  
 
 <tbody>
 
 <tr>
    <td>
        <ul>
            <li>IFNg, IL-10, TNF-a, G-CSF</li>
    </td>
 
    <td>84%</td>
 
    <td>0.91</td>
 
    <td>
        <a href="{% url 'predictor:model1' %}">
            Execute <i class="fa-solid fa-arrow-right"></i>
        </a>
    </td>
 </tr>
 
  
 
 <tr>
    <td>
        <ul>
            <li>IL6, IL4, IL1b, TNF-a, G-CSF</li>
    </td>
 
    <td>84%</td>
 
    <td>0.91</td>
 
    <td>
        <a href="{% url 'predictor:model2' %}">
            Execute <i class="fa-solid fa-arrow-right"></i>
        </a>
    </td>
 </tr>

 <tr>
    <td>
        <ul>
            <li>IL6, IL2, IL17A, IL1b, G-CSF</li>
    </td>
 
    <td>84%</td>
 
    <td>0.90</td>
 
    <td>
        <a href="{% url 'predictor:model3' %}">
            Execute <i class="fa-solid fa-arrow-right"></i>
        </a>
    </td>
 </tr>
 
  
 
  
 
 </tbody>
 
 </table>
{% endblock%} 

predictor/templates/predictor/results.html
{% extends 'base.html'%}
{% block content %}


<p>The result of the prediction is:</p>
Prediction:<b>{{output}}</b>



{% endblock%} 

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EDTools</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/d4ed401b86.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="master_bts_forms.css">

    <nav class="navbar avbar-light navbar-expand-lg" style="background-color: #F0F8FF;">
      <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
		  <a class="navbar-brand" href="{%url 'predictor:home'%}"><b>Home</b></a>
                  <a class="nav-link" href="{%url 'predictor:models'%}"><b>Models</b></a>
                  <a class="nav-link">FAQ</a> 
                  <a class="nav-link">Contact</a> 
              </div>
              
         </div>

         <div class="image-container ms-auto">
          <div class="image-container ms-auto">
              <a href = "https://www.dal.ca/" target = "_blank">
              <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/dal.png" alt="Dal Logo" width="75" height="75">
              </a>
          </div>
          
      </div>
            
        </div>
      </div>
    </nav>
</head>
<body style="display: flex; flex-direction: column; min-height: 100vh;">
    

  <div class="flex-grow-1">
    {% block content %}
    
    {% endblock %}
  </div>
  </body>

  <footer class="bg-secondary text-black text-center" style="background-color: #F0F8FF !important;">
    <a href = "https://www.dal.ca/" target = "_blank">
    <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/dal_fm.png" alt="Dal Logo" width="250" height="100">
    </a>
    <p style="margin-bottom: 3px;">Department of Microbiology & Immunology</p>
    <p style="margin-bottom: 3px;">&copy; 2023-2024 Laboratory of Emerging Infectious Diseases</p>
    <p style="margin-bottom: 3px;">Documentation</p>
    <p style="margin-bottom: 3px;">
        <a href="">
            <i class="fab fa-github"></i> GitHub
        </a>
    </p>
</footer>


</html>